user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation

app.proyecto:
    resource: "@AppBundle/Controller/ProyectoController.php"
    type: annotation
    prefix: /proyectos

app.planificacion:
    resource: "@AppBundle/Controller/PlanificacionController.php"
    type: annotation
    prefix: /planificaciones

app.tarea:
    resource: "@AppBundle/Controller/TareaController.php"
    type: annotation
    prefix: /tareas
